server:
  port: 8080
  forward-headers-strategy: FRAMEWORK

spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: suacho0724@gmail.com
    password: ngzh wuno ruac gfhx
    properties:
      mail:
        debug: true
        smtp.auth: true
        smtp.timeout: 50000
        smtp.starttls.enable: true
  data:
    redis:
      mail:
        host: localhost
        port: 6379
  jwt:
    secret: vmfhaltmskdlstkfkdgodyroqkfwkdbalroqkfwkdbalaaaaaaaaaaaaaaaabbbbb
  application:
    name: squiz
  h2:
    console:
      enabled: true
  datasource:
    url:  jdbc:h2:tcp://localhost/~/squiz
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
  servlet:
    multipart:
      max-file-size: 10GB
      max-request-size: 10GB

springdoc:
  show-login-endpoint: true
  swagger-ui:
    path: /api-details
    groups-order: desc
    tags-sorter: alpha
    operations-sorter: method
  paths-to-match:
    - /api/**

