spring:
  application:
    name: squiz
  datasource:
    url:  jdbc:h2:tcp://localhost/~/squiz
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update